// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqRvJaBlFZX09B2ozpkNb5LJSBYrOweP0',
    appId: '1:288935584617:web:699b52fa57883dda5993f8',
    messagingSenderId: '288935584617',
    projectId: 'skilnk',
    authDomain: 'skilnk.firebaseapp.com',
    databaseURL: 'https://skilnk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skilnk.firebasestorage.app',
    measurementId: 'G-YGYV966TTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5o0MGxqNMGBksqZKgNxzg5CxuZ0aGc4E',
    appId: '1:288935584617:android:a11caf74c4dfacd05993f8',
    messagingSenderId: '288935584617',
    projectId: 'skilnk',
    databaseURL: 'https://skilnk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skilnk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5AtNUY-5CRef1D1uYWj0r0j4v8jj2gAs',
    appId: '1:288935584617:ios:a3dfbea79547f1d45993f8',
    messagingSenderId: '288935584617',
    projectId: 'skilnk',
    databaseURL: 'https://skilnk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skilnk.firebasestorage.app',
    iosClientId: '288935584617-46pduq8oo1b3vqc9j22ivb0kgtgam832.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5AtNUY-5CRef1D1uYWj0r0j4v8jj2gAs',
    appId: '1:288935584617:ios:a3dfbea79547f1d45993f8',
    messagingSenderId: '288935584617',
    projectId: 'skilnk',
    databaseURL: 'https://skilnk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skilnk.firebasestorage.app',
    iosClientId: '288935584617-46pduq8oo1b3vqc9j22ivb0kgtgam832.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqRvJaBlFZX09B2ozpkNb5LJSBYrOweP0',
    appId: '1:288935584617:web:4694dcb16bbfe27c5993f8',
    messagingSenderId: '288935584617',
    projectId: 'skilnk',
    authDomain: 'skilnk.firebaseapp.com',
    databaseURL: 'https://skilnk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skilnk.firebasestorage.app',
    measurementId: 'G-BLDTTSTSGL',
  );
}
